Order page
HackYourFuture-CPH/fp-class20 pull request #146
Opened 2022-06-22 13:26 UTC by QaisSaada

# Description

Please provide a short summary explaining what this PR is about.

Fixes # (issue)

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [ ] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [ ] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [ ] This PR is ready to be merged and not breaking any other functionality

2022-06-27 12:53 UTC, Sana-Shabeel approved these changes

2022-06-27 19:02 UTC, miltonhultgren requested changes

2022-06-27 19:02 UTC, miltonhultgren commented on packages/client/src/components/Order-Page/OrderPage.component.js
> +  };
```suggestion
  useEffect(() => {
  async function fetchUser() {
    const response = await fetch(`${getApiBaseUrl()}/api/orders`, {
      method: 'GET',
      headers: { 'Content-Type': 'application/json' },
    });
    const result = await response.json();
    setData(result);
  };
  
    fetchUser();
  }, []);
```

What about loading state and error handling?

2022-06-27 19:02 UTC, miltonhultgren commented on packages/client/src/components/Order-Page/OrderPage.component.js
> +          Simply Spices / Shopping Cart and Delivery Details{' '}
```suggestion
          Simply Spices / Shopping Cart and Delivery Details
```

Use CSS margin instead

2022-06-27 19:02 UTC, miltonhultgren commented on packages/client/src/components/Order-Page/OrderPage.component.js
> +        <h1 className="order-page-title">Shopping Cart</h1>
A page with multiple `h1`s is an error. If you want the text style, then use a div and add a CSS class instead. `h1` means something very specific.

2022-06-28 08:51 UTC, QaisSaada commented on packages/client/src/components/Order-Page/OrderPage.component.js
> +  const [data, setData] = useState([]);
the best kind!

2022-06-28 09:01 UTC, QaisSaada commented on packages/client/src/components/ShoppingCart/ShoppingCart.component.js
>      );
We don't understand this. Please Mind that we "freeze code" in 5 hours. 

This entire local-storage/context thing has not been a nice learning experience. We would highly appreciate a solution at this point and we will study it later. 

I apologies if this reads as a dry comment ':)

2022-06-28 09:20 UTC, miltonhultgren commented on packages/client/src/components/ShoppingCart/ShoppingCart.component.js
>      );
Leave it for now, I will send you some learning materials to reflect on!

2022-06-28 09:26 UTC, miltonhultgren approved these changes
I'm approving because the remaining changes aren't life critical and the critical stuff is a bit too much effort for the deadline coming.

2022-06-28 09:48 UTC, merged